### ISSUE TITLE
Database schema updates

### ISSUE THREAD

**Issue by goodmami** [goodmami/wn#89]
This issue is to catalog the various changes needing to be made to the database schema, as I would like to avoid changing it frequently (most changes require a rebuild of the database).

- [x] CILI indexing changes (#23)
- [ ] ~SenseKey mapping (#55)~ (handle this outside the DB)
- [x] Reduce/remove lookup tables for constants (#75)
- [x] WN-LMF 1.0 remaining features (#65)
- [x] WN-LMF 1.1 additions (#7)
- [x] Lexicon id in extendable tables (#91)
- [x] ~Remove `lexicalized` from synsets and senses tables (#96)~
- [x] Lexicon column indicating local modifications (see #17)

**Comment by goodmami** [comment]
This was resolved when #102 was merged.
